sonar.projectKey=soen-390-makesoft
sonar.projectName=SOEN-390 MakeSoft
sonar.host.url=http://localhost:9000

sonar.sources=backend-api/src/main, mobile-app/app, mobile-app/components, mobile-app/constants, mobile-app/context, mobile-app/data, mobile-app/hooks, mobile-app/services, mobile-app/utils
sonar.tests=backend-api/src/test, mobile-app/__tests__, mobile-app/e2e

sonar.sourceEncoding=UTF-8

sonar.java.binaries=backend-api/target/classes
sonar.exclusions=**/node_modules/**,**/android/**,**/ios/**,**/assets/**,**/build/**,**/dist/**,**/target/**
sonar.test.inclusions=backend-api/src/test/**,mobile-app/__tests__/**,mobile-app/e2e/**
