logging:
  level:
    com.makesoft.app: DEBUG

server:
  port: 8081
  address: 0.0.0.0  # Allow connections from all network interfaces (not just localhost)

spring:
  application:
    name: makesoft-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: false

---
spring:
  config:
    activate:
      on-profile: "!test"
    import: optional:file:.env[.properties] # Load .env for non-test profiles only.
