logging:
  level:
    com.makesoft.app: DEBUG

server:
  port: 8080
  address: 0.0.0.0  # Allow connections from all network interfaces (not just localhost)

spring:
  application:
    name: makesoft-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: false
